# Generated by Django 4.2.6 on 2023-11-16 08:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Lyft", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="riderequest",
            name="req_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
